name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black pydantic

      # Build artefacts so tests can import/load model.pkl
      - run: python train_model.py

      - run: ruff check .
      - run: black --check .
      - run: pytest -q

      - run: docker build -t predictive-maintenance:${{ github.sha }} .
