name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black pydantic

      # Build artefacts so tests can import/load model.pkl
      - name: Train model
        run: python train_model.py

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check .

      - name: Pytest
        run: python -m pytest -q

      - name: Docker build
        run: docker build -t predictive-maintenance:${{ github.sha }} .
